### ISSUE TITLE
기능 별 함수를 분리하는게 좋아보입니다.

### ISSUE THREAD

**Issue by noggong** [verdantjuly/moviechart#1]
https://github.com/verdantjuly/moviechart/blob/0606b3949e5d021f77263453edc4fca7d937c5ba/src/index.js#L116

기능별로 좋아요, 상세보기등으로 이벤트를 각각 주고 함수도 분리하는것이 좀더 좋아보입니다.

**Comment by verdantjuly** [comment]
함수를 분리해 보겠습니다!

**Comment by verdantjuly** [comment]
제가 target.id를 이용하기 위해 이 방법을 사용했는데요~ 혹시 movie.id를 가져올 수 있는 다른 대안이 있을까요? id값을 가져와야 해당 영화에 좋아요를 하거나 디테일로 이동할 때 movie.id를 넘겨줄 수 있을 것 같아서요

**Comment by verdantjuly** [comment]
바닐라 JS가 아닌 것 에서는 onclick 방법으로 부여할 수 있다고 대면 피드백 받음!
