### ISSUE TITLE
네이밍은 의미가 명확한게 좋습니다.

### ISSUE THREAD

**Issue by noggong** [verdantjuly/moviechart#2]
https://github.com/verdantjuly/moviechart/blob/0606b3949e5d021f77263453edc4fca7d937c5ba/src/index.js#L141

a,b 이런것보단 의미있게 prev, next 등의 네이밍이 좋아보입니다.

**Comment by verdantjuly** [comment]
prev next로 업데이트 하겠습니다!

**Comment by verdantjuly** [comment]
수정하였습니다! 곧 업데이트 하겠습니다.
