### ISSUE TITLE
이벤트는 범위를 넓게 잡지 않고 각각의 element 에 이벤트 주는것이 좋습니다.

### ISSUE THREAD

**Issue by noggong** [verdantjuly/moviechart#3]
https://github.com/verdantjuly/moviechart/blob/0606b3949e5d021f77263453edc4fca7d937c5ba/src/index.js#LL118C25-L118C26

불필요한 로직과, 코드 복잡성, 애매모호할 가능성이 올라갑니다.

**Comment by verdantjuly** [comment]
고려하겠습니다!

**Comment by verdantjuly** [comment]
addEventListner를 사용하였으나 바닐라 JS가 아닌 과제에 도전 시에는 onclick 등으로 변경해 보겠습니다. 감사합니다!
