### ISSUE TITLE
이 부분의 코드가 이해되지 않습니다.

### ISSUE THREAD

**Issue by noggong** [verdantjuly/moviechart#4]
https://github.com/verdantjuly/moviechart/blob/0606b3949e5d021f77263453edc4fca7d937c5ba/src/index.js#L143

sort 가 어렵다고 작성하긴 하셨는데 여기서 length 를 왜 비교하는지 이해가 되지 않습니다.

**Comment by verdantjuly** [comment]
제가 sort를 제대로 이해하지 못해서 작성하였던 코드입니다! 음수 0 양수로 리턴되는 걸 모르고 sort를 사용하였습니다.

**Comment by verdantjuly** [comment]
다시 답변 드립니다. 전에 작성한 코드라 이해도가 늦었습니다. 해당 코드는 love 즉 좋아요가 같은 경우 title 순으로 정렬해 주는 코드입니다! 1번 정렬 기준이 좋아요이고 같으면 제목을 비교해서 알파벳순으로 sort 합니다.
