### ISSUE TITLE
함수 이름이 왜 my() 일까요?

### ISSUE THREAD

**Issue by noggong** [verdantjuly/moviechart#5]
https://github.com/verdantjuly/moviechart/blob/0606b3949e5d021f77263453edc4fca7d937c5ba/src/index.js#L136

**Comment by verdantjuly** [comment]
원래 mychart라는 차트를 여는 함수였는데  loved chart로 차트 이름을 변경하였습니다.

**Comment by verdantjuly** [comment]
loved로 함수명을 변경하겠습니다!

**Comment by verdantjuly** [comment]
openlovedchart로 변경하였습니다!
