### ISSUE TITLE
좋아요에 숫자를 넣지 않고 문자를 계속 채우는 이유가 있을까요?

### ISSUE THREAD

**Issue by noggong** [verdantjuly/moviechart#6]
https://github.com/verdantjuly/moviechart/blob/0606b3949e5d021f77263453edc4fca7d937c5ba/src/index.js#L121

**Comment by verdantjuly** [comment]
local Storage가 string으로 저장되어서 그렇게 한 것 같습니다!

**Comment by verdantjuly** [comment]
해당 기능은 수정하여 업데이트 하겠습니다! Number를 활용하여 형변환 하였습니다.
```javascript
localStorage.setItem(target.id, Number(localStorage.getItem(target.id)) + 1)
```
