### ISSUE TITLE
영화를 처음 가져올때 title 로 한번 정렬을 해준다면..

### ISSUE THREAD

**Issue by noggong** [verdantjuly/moviechart#7]
https://github.com/verdantjuly/moviechart/blob/0606b3949e5d021f77263453edc4fca7d937c5ba/src/index.js#L143

영화를 처음 가져올때 title 로 한번 정렬을 해준다면..
굳이 좋아요가 같은값을 재처리 하지 않아도 될듯합니다.

**Comment by verdantjuly** [comment]
감사합니다! 이해했습니다!

**Comment by verdantjuly** [comment]
이전에 anime라는 차트가 있었어서 그 차트를 삭제하면서 해당 기능 재정비를 하지 않은 것 같습니다. 당시에는 anime chart에 movies가 들어갔다 오면 anime 순서대로 정렬이 되어서 title순으로 한 번 더 sort 한 것 같습니다. 감사합니다!

**Comment by verdantjuly** [comment]
생각을 해 봤는데 해당 기능은 유지해야 할 것 같습니다. all chart 가 제목 순이 아닌 평점 순으로 제일 먼저 sort되기 때문에 전역변수로 설정된 movies는 해당 차트를 거치게 되면 어쩔  수 없이 좋아요 순으로 재정렬하여야 합니다. 혹시 제가 잘못 생각하고 있다면 알려 주세요!
