### ISSUE TITLE
반응형은 css 로 가능합니다.

### ISSUE THREAD

**Issue by noggong** [verdantjuly/moviechart#8]
https://github.com/verdantjuly/moviechart/blob/0606b3949e5d021f77263453edc4fca7d937c5ba/src/switch.js#L1

viewport / css @media scree 으로 해상도에 따른 반응형을 하시면 더 좋을듯 합니다.

**Comment by verdantjuly** [comment]
도전해 보겠습니다! 남겨 주신 내용은 팀 프로젝트에 반영해 보겠습니다!!!

**Comment by verdantjuly** [comment]
업데이트 드립니다! 팀 프로젝트에 반영하면 팀원들이 혼란스러울 것 같아 개인 프로젝트인 이 레포지토리에 반영하겠습니다~

**Comment by verdantjuly** [comment]
grid 를 사용하여 autofill 하였습니다!
